"""Acceptance tests for TICKET-001 (CSV promo importer).

The importer does not exist in the starter repo. This whole class is skipped
until src/panic_pantry/importer.py is implemented; then it becomes the
acceptance gate. Do not edit this file — implement the importer instead.
"""

import shutil
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from panic_pantry import store  # noqa: E402
from panic_pantry.promotions import PromotionService  # noqa: E402

try:
    from panic_pantry.importer import import_promotions  # noqa: E402

    HAS_IMPORTER = True
except ImportError:
    HAS_IMPORTER = False

CLEAN_CSV = ROOT / "fixtures" / "promos_clean.csv"
MESSY_CSV = ROOT / "fixtures" / "promos_messy.csv"
SEED = ROOT / "data" / "promotions.json.seed"


@unittest.skipUnless(
    HAS_IMPORTER, "panic_pantry.importer not implemented yet — see tickets/TICKET-001.md"
)
class ImporterContractTests(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        data_path = Path(self._tmp.name) / "promotions.json"
        shutil.copy(SEED, data_path)
        self.service = PromotionService(data_path)

    def tearDown(self):
        self._tmp.cleanup()

    def test_clean_file_creates_active_promotions(self):
        report = import_promotions(CLEAN_CSV, self.service)
        expected = ["SNACK10", "CRUNCH15", "LAUNCH12", "PRETZEL5", "NIGHT-OWL", "MIDNIGHT-SAVER"]
        self.assertEqual(report.created, expected)
        self.assertEqual(report.pending_approval, [])
        self.assertEqual(report.skipped_duplicate, [])
        self.assertEqual(report.errors, [])
        for code in expected:
            self.assertEqual(self.service.get(code).status, "active")

    def test_boundary_exactly_20_is_created_active(self):
        report = import_promotions(MESSY_CSV, self.service)
        self.assertIn("MIDNIGHT20", report.created)
        self.assertEqual(self.service.get("MIDNIGHT20").status, "active")

    def test_above_20_is_pending_and_unusable_at_checkout(self):
        report = import_promotions(MESSY_CSV, self.service)
        self.assertEqual(report.pending_approval, ["HALFOFF", "VIP25", "FREE-ALL"])
        active_codes = [p.code for p in self.service.list_active()]
        for code in ["HALFOFF", "VIP25", "FREE-ALL"]:
            self.assertEqual(self.service.get(code).status, "pending_approval")
            self.assertNotIn(code, active_codes)
            with self.assertRaises(store.PromotionNotActiveError, msg=code):
                store.apply_promotion(self.service, code, 1000)

    def test_created_rows_in_file_order(self):
        report = import_promotions(MESSY_CSV, self.service)
        self.assertEqual(report.created, ["CRUNCH10", "MIDNIGHT20"])

    def test_malformed_rows_reported_with_line_numbers(self):
        report = import_promotions(MESSY_CSV, self.service)
        error_lines = [line for line, _reason in report.errors]
        self.assertEqual(error_lines, [9, 10, 11, 12, 13, 14])
        for line, reason in report.errors:
            self.assertIsInstance(reason, str, msg=f"line {line}")
            self.assertTrue(reason.strip(), msg=f"line {line} has an empty reason")

    def test_in_file_duplicate_skipped_not_overwritten(self):
        report = import_promotions(MESSY_CSV, self.service)
        self.assertIn("CRUNCH10", report.skipped_duplicate)
        # line 2 created CRUNCH10 at 10%; the line 7 duplicate (15%) must not win
        self.assertEqual(self.service.get("CRUNCH10").discount_pct, 10)

    def test_pre_existing_duplicate_skipped_not_overwritten(self):
        report = import_promotions(MESSY_CSV, self.service)
        self.assertIn("WELCOME10", report.skipped_duplicate)
        promo = self.service.get("WELCOME10")
        self.assertEqual(promo.discount_pct, 10)
        self.assertEqual(promo.status, "active")

    def test_second_run_is_idempotent(self):
        first = import_promotions(MESSY_CSV, self.service)
        active_after_first = sorted(p.code for p in self.service.list_active())
        second = import_promotions(MESSY_CSV, self.service)
        self.assertEqual(second.created, [])
        self.assertEqual(second.pending_approval, [])
        for code in first.created + first.pending_approval:
            self.assertIn(code, second.skipped_duplicate)
        self.assertEqual(
            sorted(p.code for p in self.service.list_active()), active_after_first
        )

    def test_missing_header_reported_and_nothing_imported(self):
        headerless = Path(self._tmp.name) / "no_header.csv"
        headerless.write_text("SNEAKY99,99\n", encoding="utf-8")
        before = sorted(p.code for p in self.service.list_active())
        report = import_promotions(headerless, self.service)
        self.assertEqual([line for line, _ in report.errors], [1])
        self.assertEqual(report.created, [])
        self.assertEqual(report.pending_approval, [])
        self.assertIsNone(self.service.get("SNEAKY99"))
        self.assertEqual(sorted(p.code for p in self.service.list_active()), before)


if __name__ == "__main__":
    unittest.main()
